"""Monte-Carlo equity helpers.

* ``equity_vs_random(hole, board, n_opponents, samples, rng)`` – share of the pot
  our hand wins against ``n_opponents`` uniformly random hands, board run out to
  the river.  Used by heuristic bots as a crude "hand strength".
* ``preflop_percentile(class_name)`` – 0..1 rank of a 169-class starting hand
  (1.0 = AA) from a precomputed 6-max equity table.  The table is generated by
  ``scripts/gen_preflop_table.py`` and shipped as ``preflop_equity_6max.json``.
"""
from __future__ import annotations

import json
import os
import random
from functools import lru_cache
from typing import Dict, List, Optional, Sequence

from .cards import ALL_HOLE_CLASSES, hole_class
from .evaluator import evaluate

_TABLE_PATH = os.path.join(os.path.dirname(__file__), "preflop_equity_6max.json")


def equity_vs_random(
    hole: Sequence[int],
    board: Sequence[int],
    n_opponents: int = 1,
    samples: int = 200,
    rng: Optional[random.Random] = None,
) -> float:
    """Fraction of pot won (ties split) versus random opponent hands."""
    rng = rng or random.Random()
    used = set(hole) | set(board)
    deck = [c for c in range(52) if c not in used]
    need_board = 5 - len(board)
    n_draw = need_board + 2 * n_opponents
    won = 0.0
    hole_l = list(hole)
    board_l = list(board)
    for _ in range(samples):
        drawn = rng.sample(deck, n_draw)
        full_board = board_l + drawn[:need_board]
        my = evaluate(hole_l + full_board)
        best_opp = -1
        ties = 0
        for k in range(n_opponents):
            o = drawn[need_board + 2 * k : need_board + 2 * k + 2]
            v = evaluate(o + full_board)
            if v > best_opp:
                best_opp = v
                ties = 1
            elif v == best_opp:
                ties += 1
        if my > best_opp:
            won += 1.0
        elif my == best_opp:
            won += 1.0 / (ties + 1)
    return won / samples


# ---- fast backend hook (negpluribus/fast): identical draws from the caller's random.Random
# (state handed to C++ and back), so results are bit-identical; NEGPLURIBUS_FAST_EVAL=0 disables.
equity_vs_random_py = equity_vs_random
try:
    from .fast.equity import make_fast_equity as _make_fast_equity

    _fast_equity = _make_fast_equity(equity_vs_random_py)
except Exception:  # pragma: no cover
    _fast_equity = None
if _fast_equity is not None:
    equity_vs_random = _fast_equity


@lru_cache(maxsize=1)
def _load_table() -> Dict[str, float]:
    if not os.path.exists(_TABLE_PATH):
        raise FileNotFoundError(
            "preflop table missing; run `python scripts/gen_preflop_table.py`"
        )
    with open(_TABLE_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


@lru_cache(maxsize=1)
def _percentiles() -> Dict[str, float]:
    tbl = _load_table()
    ordered = sorted(ALL_HOLE_CLASSES, key=lambda k: tbl[k])
    n = len(ordered)
    return {k: (i + 1) / n for i, k in enumerate(ordered)}


def preflop_equity(class_name: str) -> float:
    """Raw 6-way all-in equity of a starting-hand class vs 5 random hands."""
    return _load_table()[class_name]


def preflop_percentile(class_name: str) -> float:
    """0..1, where 1.0 is the best starting hand (AA)."""
    return _percentiles()[class_name]


def hole_percentile(c1: int, c2: int) -> float:
    return preflop_percentile(hole_class(c1, c2))


def top_hands(fraction: float) -> List[str]:
    """Starting-hand classes in the top ``fraction`` by 6-max equity."""
    pct = _percentiles()
    return [k for k in ALL_HOLE_CLASSES if pct[k] > 1.0 - fraction]
